import React from 'react';

const Terms = () => {
    return (
        <div className="container" style={{ marginTop: "10rem", paddingBottom: "5rem" }}>
            <div className='text-center'>
                <div className='section-title'>
                    <h2>Terms</h2>
                </div>
            </div>
            <div className="col-md-9 body-padding">
                <div className="row">
                    <div className="col-md-12 body-padding">
                        <h1 className="main-sub-heading">KK Cash terms and conditions and disclaimer</h1>
                        <h3 className="sub-heading">Introduction</h3>
                        <p>This is the website of KK Cash Online (Pty) Limited, (Registration No. 2021/377150/07) (KK Cash, us, our, we), a private company registered in the Republic of South Africa.</p>
                        <p>KK Cash is a registered credit provider (NCRCP12875).</p>
                        <p>You can contact us regarding this website by email, at <a href="/cdn-cgi/l/email-protection#72110701061d1f17001113001732051d1c15135c111d5c0813" title=" customercare@KK Cash.co.za"><span className="__cf_email__" data-cfemail="6605131512090b031405071403261109080107480509481c07">[email&#160;protected]</span></a></p>
                        <p>KK Cash provides the information contained in this website and the pages comprising the website, and advertises and offers the services advertised on this website from time to time ("service/s") to users ("you"), subject to the terms and conditions set out herein ("the terms").</p>
                        <p>Please read these terms, together with our Privacy Policy carefully, they will govern our relationship with you in relation to your use of <a href="/" title="KK Cash Online">www.KK Cash.co.za</a> ("the website") and will constitute an ongoing binding agreement between KK Cash and yourself.</p>
                        <h3 className="sub-heading">Acceptance of Terms</h3>
                        <p>By accessing the website, you are deemed to have read, understood and agreed to the terms. KK Cash may at any time modify any of the terms and such modification will supercede and replace any previous terms. The amended terms will be made available on the website. Each time you access the website, you agree to be bound by the terms, as they have changed.</p>
                        <p>If you do not accept these terms and conditions, please do not continue to use this website. Please note that the terms and conditions stated in this document refer to the use by you of this website and are not related to any commercial agreement concluded between you and KK Cash or any other third party pursuant to the use of this website.</p>
                        <h3 className="sub-heading">Content of the website</h3>
                        <p>While KK Cash makes every effort to update the information provided on the website on a regular basis, KK Cash makes no representations or warranties, whether express, implied in law or residual, as to the accuracy, completeness or reliability of any information, data and/or content on the website.</p>
                        <p>The information, ideas and opinions expressed on this website are of a general nature and should not be regarded as financial or other advice. Before making any decision or taking any action based on, or in relation to information, ideas and opinions expressed on this website which might affect your personal finances or business, you should take appropriate advice from a suitably qualified person.</p>
                        <p>KK Cash has offices in South Africa and alliances with companies outside South Africa. However, content related to the products and services featured on this website are based on the laws of South Africa unless otherwise expressly stated. Your use of this website and any dispute arising out of the website is subject to the laws of South Africa. Any dispute arising out of the use or publication of this website is subject to the exclusive jurisdiction of the courts of South Africa.</p>
                        <h3 className="sub-heading">Use of the website and indemnification</h3>
                        <p>By accessing the website, you warrant and represent to KK Cash that you are legally entitled to do so. If you subscribe for any of our products you warrant and represent that you are legally authorised to subscribe for such services. You further warrant you will not use the website, the products and/or the services or any information made available or sent to you by us pursuant to your use of the website for any purpose that is unlawful or prohibited under South African or international law or is contravention of the terms. You hereby indemnify KK Cash against any loss, liability, damage or expense of whatever nature which KK Cash or any third party may suffer which is caused by or attributable to, whether directly or indirectly, a breach by you of any of the warranties in these terms.</p>
                        <p>This website is available to you for your non-commercial use.</p>
                        <p>We may modify, withdraw or deny access to this website at any time.</p>
                        <p>You may print pages for your personal use but no part of this website may be reproduced or transmitted for any other purpose.</p>
                        <p>This website is intended to provide general information regarding KK Cash, our products and services, and other information which may be of interest to you. It is not intended to provide exhaustive treatment of any subject. The information on this website including all research, opinions or other content is not intended to and does not constitute financial, accounting, tax, legal, investment, consulting or other professional advice or services. Before making any decision or taking any action which might affect your personal finances or business you should take appropriate advice from a suitably qualified person.</p>
                        <h3 className="sub-heading">Copyright and Intellectual Property</h3>
                        <p>Copyright and all intellectual property rights and all materials, texts, drawings and data made available on the website (collectively "the materials") are owned by KK Cash, alternatively KK Cash is the lawful user thereof, and are protected by both South African and international intellectual property laws. Any unauthorised copying, reproduction, retransmission, distribution, dissemination, sale, publication, broadcast or other circulation or exploitation of such material or any component thereof will be an infringement of such copyright and other intellectual property rights; save that you may use the materials or any component thereof for your own internal purposes and for purposes of considering and making use of the services offered by KK Cash. The trademarks, names, logos and service marks (collectively "trademarks") displayed on this website are registered and unregistered trademarks of KK Cash. Nothing contained on this website should be construed as granting any licence or right to use any trademark without the prior written permission of KK Cash.</p>
                        <h3 className="main-sub-heading sub-heading">Third party links</h3>
                        <p>From time to time this website may also include links to other websites. These links are provided in order to enhance the interest of other featured content and are not intended to signify that KK Cash endorses or otherwise has any responsibility for the content of the linked website.</p>
                        <p>No endorsement or approval of any third party or their advice, opinions, information, products or services is expressed or implied by any information on this website.</p>
                        <p>External links may be provided for your convenience, but they are beyond the control of KK Cash and no representation is made as to their content. Use or reliance on any external links provided is at your own risk. When visiting external links you must refer to the external terms and conditions of use. No hypertext links shall be created from any website controlled by you or otherwise to this website without the express prior written permission of KK Cash.</p>
                        <h3 className="sub-heading">Permission to link to our website</h3>
                        <p>Nobody may establish a hyperlink, frame, meta tag or similar reference, whether electronically or otherwise (collectively referred to as linking), to this site or any subsidiary pages before receiving KK Cash's prior written approval, which may be withheld or granted subject to the conditions KK Cash specifies from time to time.</p>
                        <h3 className="sub-heading">Framing</h3>
                        <p>No person, business or website may frame the site of KK Cash or any of the pages on this site in any way whatsoever.</p>
                        <h3 className="sub-heading">Crawlers and spiders</h3>
                        <p>No person, business or website may use any technology to search and/or gain information from KK Cash's website without its prior written consent.</p>
                        <h3 className="sub-heading">Warranties, disclaimers and limitation of liability</h3>
                        <p>Save as set out in the terms, KK Cash makes no warranties, representations, statements or guarantees (whether express, implied in law or residual) regarding the website and the service/s and the website and service/s made available via the website are provided "as is". KK Cash does not make any warranty or representation that information and service/s advertised on the website are appropriate for use in any jurisdiction.</p>
                        <p>To the fullest extent possible by law, KK Cash expressly disclaims all (express or implied) warranties, including, without limitation, warranties and non-infringement, compatibility, security and accuracy in respect of this website. We do not warrant that the website or any software available for download via the website is free of viruses or destructive codes.</p>
                        <p>Neither KK Cash or its directors shall be responsible for, and they hereby disclaim all liability for, any loss, liability, damage (whether direct, indirect or consequential) and/or expense of any nature whatsoever which may be suffered by you or any third party, as a result of or which may be attributable, directly or indirectly, to your access and use of the website and/or any information contained on or received via the website, your use of the service/s and/or your reliance on any information offered via the website and service/s.</p>
                        <p>Without limiting the generality of the aforegoing, neither KK Cash nor its directors shall be liable for any loss of business, loss of data and/or loss of profits, any failure and/or unavailability of the website for any reason whatever and/or the failure/delay by any third party service provider to render any service/s which are necessary to ensure the availability of the website.</p>
                        <p>Information transmitted via the internet is susceptible to monitoring and interception. You will bear all risks of transmitting information in this manner. We will not be liable for any loss, harm or damage suffered by you as a result of transmitting information to us.</p>
                        <p>Any unsolicited confidential or proprietary information sent to us via the internet cannot be guaranteed to remain confidential. If you need to send such information to us and are concerned about the security of this information please contact us and we will advise you of the most appropriate method of transmission.</p>
                        <p>This website is made available for public viewing on the basis that KK Cash excludes, to the extent lawfully permitted all liability whatsoever for any loss or damage howsoever arising out of the use of this website or reliance upon the content of this website.</p>
                        <p>Nothing on this website is intended to be nor should be construed as an offer to enter into a contractual relationship with you or anyone else, except for these terms which govern the relationship between us in relation to your use of the website. The advertising of our services via the website merely constitutes an invitation by KK Cash for you to make an application for credit. KK Cash reserves the right not to accept and/or comply with any application for any reason whatsoever on notice to you. Should KK Cash accept your application for credit, the agreement is governed by the terms and conditions of the application and loan agreement itself and not by these terms which specifically relate to the use of the website.</p>
                        <h3 className="sub-heading">Compliance with Legislation</h3>
                        <p>KK Cash will not tolerate anyone using the KK Cash website (including the loan application process) in contravention of any law, whether in common law or statute, and reserves the right to take action against anyone doing so, including laying a criminal charge, where applicable.</p>
                        <h3 className="sub-heading">Privacy Policy </h3>
                        <p>We respect your privacy and your personal information (even if you do not become or are no longer a customer of ours) and refer you to our privacy policy which governs the way in which we collect and use the personal information provided to us as part of the application process. You give KK Cash permission to collect and use your personal information when you use the website.</p>
                    </div>
                </div>
            </div>
        </div>
    )
}

export default Terms;